CREATE SCHEMA BUSINESS;

CREATE TABLE BUSINESS.DIM_DATE
(
    DATE_KEY        INT PRIMARY KEY,       -- YYYYMMDD
    FULL_DATE       DATE,
    DAY_NUMBER      INT,
    MONTH_NUMBER    INT,
    MONTH_NAME      VARCHAR(20),
    QUARTER_NUMBER  INT,
    YEAR_NUMBER     INT,
    DAY_OF_WEEK     VARCHAR(20)
);


CREATE TABLE BUSINESS.DIM_CUSTOMER
(
    CUSTOMER_KEY        BIGINT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(100),
    FULL_NAME           VARCHAR(200),
    AGE                 INT,
    GENDER              VARCHAR(20),
    CITY                VARCHAR(100),
    STATE               VARCHAR(100),
    EMPLOYMENT_TYPE     VARCHAR(50),
    ANNUAL_INCOME       DECIMAL(18,2),
    KYC_STATUS          VARCHAR(20),
    CUSTOMER_STATUS     VARCHAR(20),

    EFFECTIVE_FROM      DATE,
    EFFECTIVE_TO        DATE,
    IS_CURRENT          BIT
);

CREATE TABLE BUSINESS.DIM_DEVICE
(
    DEVICE_KEY      BIGINT IDENTITY(1,1) PRIMARY KEY,
    DEVICE_ID       VARCHAR(200),
    APPLICATION_ID  VARCHAR(200),
    DEVICE_TYPE     VARCHAR(50),
    OS_VERSION      VARCHAR(50),
    BROWSER         VARCHAR(100),
    IP_ADDRESS      VARCHAR(100),
    LATITUDE        DECIMAL(10,6),
    LONGITUDE       DECIMAL(10,6)
);

CREATE TABLE BUSINESS.DIM_CREDIT_PROFILE
(
    CREDIT_KEY          BIGINT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(100),
    CREDIT_SCORE        INT,
    CREDIT_SCORE_BAND   VARCHAR(50),
    PAST_DEFAULTS       INT,
    ACTIVE_LOANS        INT,
    ENQUIRIES_LAST_6M   INT,
    REPORT_DATE         DATE
);


CREATE TABLE BUSINESS.FACT_LOAN_APPLICATION
(
    APPLICATION_KEY     BIGINT IDENTITY(1,1) PRIMARY KEY,
    APPLICATION_ID      VARCHAR(100),

    CUSTOMER_KEY        BIGINT,
    DATE_KEY            INT,
    DEVICE_KEY          BIGINT,
    CREDIT_KEY          BIGINT,

    REQUESTED_AMOUNT    DECIMAL(18,2),
    TENURE_MONTHS       INT,
    INTEREST_RATE       DECIMAL(5,2),

    FRAUD_FLAG          BIT,             -- 0 = GENUINE, 1 = FRAUD
    FRAUD_REASON        VARCHAR(200),

    APPLICATION_COUNT   INT DEFAULT 1
);
